export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALIED = "LOGIN_FALIED";
export const LOG_OUT = "LOG_OUT";

export const API_REQUEST = "API_REQUEST";
export const SUCCESS_RESPONSE = "SUCCESS_RESPONSE";
export const ERROR_RESPONSE = "ERROR_RESPONSE";
export const SET_COMMON_STATUS = "SET_COMMON_STATUS"
export const SKIP_ONBOARDING = "SKIP_ONBOARDING";
export const SKIP_INTRO = "SKIP_INTRO";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const SET_QUESTIONS = "SET_QUESTIONS"

export const GET_FLEXERS = "GET_FLEXERS"
export const GET_FRIENDREQUEST = "GET_FRIENDREQUEST"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const SET_NUM_FRIENDS = "SET_NUM_FRIENDS"
export const SET_NUM_MESSAGES = "SET_NUM_MESSAGES"

export const SET_GYMDETAIL = "SET_GYMDETAIL"
export const GET_GYM_BY_ID = "GET_GYM_BY_ID"
export const SET_GYMDETAIL_BY_ID = "SET_GYMDETAIL_BY_ID"

export const GET_WALLET_AMOUNT = "GET_WALLET_AMOUNT"

export const SET_LOCALGYM_ID = "SET_LOCALGYM_ID";
export const FRIEND_REQUEST_FROM_OTHERS = "FRIEND_REQUEST_FROM_OTHERS";
export const ONLINE_USERS = "ONLINE_USERS";

export const FRIEND_REQUEST = "FRIEND_REQUEST";